[package]
name = "donut_2_in_rust"
version = "0.1.0"
authors = ["joao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slice-fill = "1.0.1"
